In [86]:
#1. Create a NumPy array arr of integers from 0 to 5 and print its data type. 
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int32


In [87]:
#2. Given a NumPy array arr, check if its data type is float64.
print(arr.dtype == np.float64)



False


In [88]:
# 3. Create a NumPy array arr with a data type of complex128 containing three
# complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)



[1.+2.j 3.+4.j 5.+6.j]


In [89]:
#4. Convert an existing NumPy array arr of integers to float32 data type.
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)



[1. 2. 3. 4. 5.]


In [90]:
# 5 Given a NumPy array arr with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)



[1.1 2.2 3.3]


In [91]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype



In [92]:
# 7. Create a function array_dimension that returns the dimensionality of a NumPy array.
def array_dimension(arr):
    return arr.ndim



In [93]:
# 8. Design a function item_size_info that returns the item size and total size in bytes
# of a NumPy array.

def item_size_info(arr):
    return arr.itemsize, arr.nbytes



In [94]:
# 9. Create a function array_strides that returns the strides of the given NumPy array.
def array_strides(arr):
    return arr.strides


In [95]:
#10. Design a function shape_stride_relationship that returns the shape andstrides of the given array. 
def shape_stride_relationship(arr):
    return arr.shape, arr.strides


In [96]:
# Array Creation
# 11. Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements. 
def create_zeros_array(n):
    return np.zeros(n)



In [97]:
#12. Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))



In [98]:
#13. Write a function generate_range_array(start, stop, step) to create a ranged NumPy array.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)



In [99]:
# 14. Design a function generate_linear_space(start, stop, num) for equally
# spaced values. 
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)


In [100]:
# 15. Create a function create_identity_matrix(n) using numpy.eye.
def create_identity_matrix(n):
    return np.eye(n)



In [101]:
# 16. Write a function that converts a Python list into a NumPy array.
def list_to_numpy(lst):
    return np.array(lst)


In [102]:
# 17. Create a NumPy array and use numpy.view() to create a new view with the same
# data. 
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
print(view_arr)


[1 2 3 4]


In [103]:
# Concatenation and Stacking
# 18. Write a function to concatenate two NumPy arrays along a specified axis.

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)


In [104]:
# 19. Concatenate two arrays with different shapes horizontally using
# numpy.concatenate.


arr1 = np.array([[1], [2]])
arr2 = np.array([[3, 4]])
print(np.concatenate((arr1, arr2.T), axis=1))


[[1 3]
 [2 4]]


In [105]:
# 20. Vertically stack multiple arrays from a list using numpy.vstack.
# Array Generation
def vertical_stack(arr_list):
    return np.vstack(arr_list)



In [106]:
# 21. Write a function to generate an array of integers within a specified range (inclusive)
# with a step.
def generate_range(start, stop, step):
    return np.arange(start, stop+1, step)


In [107]:
# 22. Generate 10 equally spaced values between 0 and 1 using NumPy.
print(np.linspace(0, 1, 10))



[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [108]:
# 23. Create 5 logarithmically spaced values between 1 and 1000.
# Pandas + NumPy 
print(np.logspace(0, 3, 5, base=10))



[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [109]:
# 24. Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of
# random integers (1-100).
import pandas as pd
array = np.random.randint(1, 101, (5, 3))
df = pd.DataFrame(array)
print(df)


    0    1   2
0  94   71  55
1  35   91  22
2  69   94  15
3  99  100  35
4  37   69  90


In [110]:
# 25. Write a function to replace all negative values in a specific column with zeros using
# NumPy.
def replace_negatives_with_zero(arr):
    arr[arr < 0] = 0
    return arr


In [111]:
# Indexing and Slicing
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40])
print(arr[2])


30


In [112]:
# 27. Retrieve the element at index (1, 2) from a 2D array.
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[1, 2])

6


In [113]:
# 28. Extract elements greater than 5 using boolean indexing.
arr = np.array([1, 6, 3, 8, 5])
print(arr[arr > 5])


[6 8]


In [114]:
# 29. Slice elements from index 2 to 5 (inclusive) from a NumPy array.
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[2:6])



[2 3 4 5]


In [115]:
# 30. Slice the sub-array [[2, 3], [5, 6]] from a 2D array.
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[[0,1],1:3])


[[2 3]
 [5 6]]


In [116]:
# Advanced Indexing
# 31. Extract elements based on indices from a 2D array.
arr2d = np.array([[1, 2], [3, 4]])
indices = [0, 1]
print(arr2d[indices])



[[1 2]
 [3 4]]


In [117]:
# 32. Filter elements greater than a threshold using boolean indexing.
arr = np.array([1, 6, 3, 8, 5])
print(arr[arr > 4])



[6 8 5]


In [118]:
# 33. Extract specific elements from a 3D array using separate index arrays.
arr = np.arange(27).reshape(3, 3, 3)
print(arr[[0,1],[1,2],[2,0]])


[ 5 15]


In [119]:
# 34. Return elements satisfying two boolean conditions.
arr = np.array([1, 6, 3, 8, 5])
print(arr[(arr > 2) & (arr < 7)])


[6 3 5]


In [120]:
# 35. Extract elements from a 2D array using separate row and column index arrays.
arr2d = np.array([[10, 20, 30], [40, 50, 60]])
rows = [0, 1]
cols = [1, 2]
print(arr2d[rows, cols])


[20 60]


In [121]:
# Broadcasting
# 36. Add scalar 5 to every element of an array using broadcasting.
arr = np.array([1, 2, 3])
print(arr + 5)


[6 7 8]


In [122]:
# 37. Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array.

arr = np.ones((3, 4))
mul = np.array([[1], [2], [3]])
print(arr * mul)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [123]:
# 38. Add a (1, 4) array to every row of a (4, 3) array using broadcasting.

arr = np.ones((4, 3))
add = np.array([[1, 2, 3, 4]]).T
print(arr + add)



[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]


In [124]:
# 39. Add two arrays of shapes (3, 1) and (1, 3) using broadcasting.
arr1 = np.ones((3,1))
arr2 = np.ones((1,3))
print(arr1 + arr2)



[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [125]:
# 40. Handle shape incompatibility during multiplication between (2, 3) and (2, 2) arrays

try:
    arr1 = np.ones((2,3))
    arr2 = np.ones((2,2))
    print(arr1 * arr2)
except ValueError as e:
    print("Incompatible shapes:", e)


Incompatible shapes: operands could not be broadcast together with shapes (2,3) (2,2) 


In [126]:
# Aggregations and Statistics
# 41. Calculate column-wise mean of a 2D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis=0))


[2.5 3.5 4.5]


In [127]:
# 42. Find maximum value in each row.
print(np.max(arr, axis=1))


[3 6]


In [128]:
# 43. Find indices of maximum values in each column.
print(np.argmax(arr, axis=0))


[1 1 1]


In [129]:
# 44. Apply a custom function to compute moving sum along rows.
def moving_sum(arr, window):
    return np.convolve(arr, np.ones(window, dtype=int), 'valid')


In [130]:
# 45. Check if all elements in each column are even.
print(np.all(arr % 2 == 0, axis=0))


[False False False]


In [131]:
# Reshaping and Flattening
# 46. Reshape a given array into dimensions m x n.
arr = np.arange(12)
print(arr.reshape(3,4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [132]:
# 47. Return a flattened version of a given matrix.
matrix = np.array([[1,2],[3,4]])
print(matrix.flatten())


[1 2 3 4]


In [133]:
# 48. Concatenate two arrays along a specified axis.
arr1 = np.array([1,2])
arr2 = np.array([3,4])
print(np.concatenate((arr1, arr2)))


[1 2 3 4]


In [134]:
# 49. Split an array into sub-arrays along a specified axis.
arr = np.array_split(np.arange(10), 2)
print(arr)


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [135]:
# 50. Insert and delete elements at specified indices from an array.
arr = np.array([1, 2, 3, 4, 5])
arr = np.insert(arr, 2, 99)
arr = np.delete(arr, 4)
print(arr)


[ 1  2 99  3  5]


In [136]:
# Element-wise Operations
# 51. Perform element-wise addition between two arrays.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)


[5 7 9]


In [137]:
# 52. Perform element-wise subtraction: subtract arr2 from arr1.
print(arr1 - arr2)


[-3 -3 -3]


In [138]:
# 53. Perform element-wise multiplication.
print(arr1 * arr2)


[ 4 10 18]


In [139]:
# 54. Divide elements of arr1 by arr2 element-wise.
print(arr1 / arr2)


[0.25 0.4  0.5 ]


In [140]:
# 55. Perform element-wise exponentiation: arr1 ** arr2.
print(arr1 ** arr2)


[  1  32 729]


In [141]:
# String Operations
# 56. Count occurrences of a substring in a string array.
str_arr = np.array(["apple apple", "banana", "apple"])
print(np.char.count(str_arr, "apple"))


[2 0 1]


In [142]:
# 57. Extract uppercase characters from a string array.
str_arr = np.array(["Hello", "WORLD", "NumPy"])
print(["".join(filter(str.isupper, s)) for s in str_arr])


['H', 'WORLD', 'NP']


In [143]:
# 58. Replace substring occurrences with another string in a string array.
print(np.char.replace(str_arr, "apple", "orange"))


['Hello' 'WORLD' 'NumPy']


In [144]:
# 59. Concatenate strings in a NumPy array element-wise.
print(np.char.add(["a", "b"], ["x", "y"]))


['ax' 'by']


In [145]:
# 60. Find the length of the longest string in a string array.
print(max([len(s) for s in str_arr]))


5


In [146]:
# Descriptive Statistics
# 61. Generate 100 random integers (1–1000) and compute mean, median, variance, and
# std deviation.
data = np.random.randint(1, 1001, 100)
print(np.mean(data), np.median(data), np.var(data), np.std(data))


497.75 474.5 82939.4075 287.9920267993543


In [147]:
# 62. Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles.
data = np.random.randint(1, 101, 50)
print(np.percentile(data, 25), np.percentile(data, 75))


25.0 56.0


In [148]:
# 63. Compute correlation coefficient between two arrays using np.corrcoef.
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.corrcoef(x, y))


[[1. 1.]
 [1. 1.]]


In [149]:
# 64. Perform matrix multiplication using np.dot.
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
print(np.dot(A, B))


[[ 4  4]
 [10  8]]


In [150]:
# 65. Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50
# integers.
data = np.random.randint(1, 101, 50)
print(np.percentile(data, [10, 50, 90]))


[13.  55.  87.3]


In [151]:
# Search and Sort
# 66. Find index of a specific element in an array.
arr = np.array([10, 20, 30, 40])
print(np.where(arr == 30))


(array([2], dtype=int64),)


In [152]:
# 67. Sort a random array in ascending order.
arr = np.random.randint(1, 100, 10)
print(np.sort(arr))


[ 2 35 42 57 69 72 81 88 89 98]


In [153]:
# 68. Filter elements greater than 20.
print(arr[arr > 20])


[72 81 42 69 88 57 98 89 35]


In [154]:
# 69. Filter elements divisible by 3.
print(arr[arr % 3 == 0])

[72 81 42 69 57]


In [155]:
# 70. Filter elements between 20 and 40 (inclusive).
print(arr[(arr >= 20) & (arr <= 40)])



[35]


In [156]:
# Byte Order & Swapping
# 71. Check byte order of a NumPy array using dtype.byteorder.
arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)


=


In [157]:
# 72. Perform in-place byte swapping using byteswap().
print(arr.byteswap(inplace=True))

[16777216 33554432 50331648]
